name: effisegnet_torch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.11

  # PyTorch ecosystem
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8  # For CUDA support, adjust version as needed

  # Deep Learning frameworks
  - pytorch-lightning>=2.0.0

  # Medical imaging
  - monai>=1.2.0

  # Configuration management
  - hydra-core>=1.3.0

  # Image processing
  - pillow>=9.0.0

  # Scientific computing
  - numpy>=1.21.0

  # Progress bars and utilities
  - tqdm

  # Tensorboard for logging
  - tensorboard

  # Additional utilities that might be needed
  - matplotlib  # For visualization
  - scikit-learn  # For metrics
  - opencv  # For advanced image processing

  # Development tools
  - pip

  # Pip dependencies (if needed)
  - pip:
    - timm>=0.9.0  # Transformer models library (if you want to use timm models)
    # Add any other pip-only packages here if needed

# Usage instructions:
# 1. Create environment: conda env create -f environment.yaml
# 2. Activate environment: conda activate effisegnet_torch
# 3. Update environment: conda env update -f environment.yaml --prune

